---
title: "SR chapter 4 practices"
author: "Manon Grandjean"
date: "2/12/2021"
output: html_document
---

# 4.7. Practice
Problems are labeled Easy (E), Medium (M), and Hard (H).
*My answers are marked in italics*

### Easy
4E1. In the model definition below, which line is the likelihood? 
  *yi ∼ Normal(μ, σ)*
  μ ∼ Normal(0, 10) 
  σ ∼ Exponential(1)
*- initial thinking: if mu is mean and sigma is standard deviation (SR 4.3) then yi could be likelihood given the two others?)*
*- it is also stated on page 82 where instead of yi it is called hi*

4E2. In the model definition just above, how many parameters are in the posterior distribution?
*- 2? mu and sigma (see also page 82: "The parameters to be estimated are both μ and σ, so we need a prior Pr(μ, σ), the joint prior probability for all parameters.")*

4E3. Using the model definition above, write down the appropriate form of Bayes’ theorem that includes the proper likelihood and priors.
*(see SR page 84 for where i took it from and modified it)*
*(for mathematical notation in R: https://rpruim.github.io/s341/S19/from-class/MathinRmd.html)*
$Pr(\mu, \sigma|y) = \frac{\prod_{i} Normal(y_{i}|\mu, \sigma)Normal(\mu|0, 10)Exponential(\sigma|1)}{\int\int\prod_{i} Normal(y_{i}|\mu, \sigma)Normal(\mu|0, 10)Exponential(\sigma|1)d\mu d\sigma}$

4E4. In the model definition below, which line is the linear model?
  yi ∼ Normal(μ, σ) 
  *μi =α+βxi*
  α ∼ Normal(0, 10) 
  β ∼ Normal(0, 1) 
  σ ∼ Exponential(2)

4E5. In the model definition just above, how many parameters are in the posterior distribution? 
*3? α, β, and σ*

### Medium
4M1. For the model definition below, simulate observed y values from the prior (not the posterior).
  yi ∼ Normal(μ, σ) 
  μ ∼ Normal(0, 10) 
  σ ∼ Exponential(1)

4M2. Translate the model just above into a quap formula.

4M3. Translate the quap model formula below into a mathematical model definition.
    y ~ dnorm( mu , sigma ),
    mu <- a + b*x,
    a ~ dnorm( 0 , 10 ),
    b ~ dunif( 0 , 1 ),
    sigma ~ dexp( 1 )

4M4. A sample of students is measured for height each year for 3 years. After the third year, you want to fit a linear regression predicting height using year as a predictor. Write down the mathematical model definition for this regression, using any variable names and priors you choose. Be prepared to defend your choice of priors.

4M5. Now suppose I remind you that every student got taller each year. Does this information lead you to change your choice of priors? How?

4M6. Now suppose I tell you that the variance among heights for students of the same age is never more than 64cm. How does this lead you to revise your priors?

4M7. Refit model m4.3 from the chapter, but omit the mean weight xbar this time. Compare the new model’s posterior to that of the original model. In particular, look at the covariance among the parameters. What is different? Then compare the posterior predictions of both models.

4M8. In the chapter, we used 15 knots with the cherry blossom spline. Increase the number of knots and observe what happens to the resulting spline. Then adjust also the width of the prior on the weights—change the standard deviation of the prior and watch what happens. What do you think the combination of knot number and the prior on the weights controls?

### Hard
4H1. The weights listed below were recorded in the !Kung census, but heights were not recorded for these individuals. Provide predicted heights and 89% intervals for each of these individuals. That is, fill in the table below, using model-based predictions.
Individual     weight                           expected height       89% interval
1 2 3 4 5      46.95 43.72 64.78 32.59 54.63

4H2. Select out all the rows in the Howell1 data with ages below 18 years of age. If you do it right, you should end up with a new data frame with 192 rows in it.
  (a) Fit a linear regression to these data, using quap. Present and interpret the estimates. For every 10 units of increase in weight, how much taller does the model predict a child gets?
  (b) Plot the raw data, with height on the vertical axis and weight on the horizontal axis. Super- impose the MAP regression line and 89% interval for the mean. Also superimpose the 89% interval for predicted heights.
  (c) What aspects of the model fit concern you? Describe the kinds of assumptions you would change, if any, to improve the model. You don’t have to write any new code. Just explain what the model appears to be doing a bad job of, and what you hypothesize would be a better model.

4H3. Suppose a colleague of yours, who works on allometry, glances at the practice problems just above. Your colleague exclaims, “That’s silly. Everyone knows that it’s only the logarithm of body weight that scales with height!” Let’s take your colleague’s advice and see what happens.
  (a) Model the relationship between height (cm) and the natural logarithm of weight (log-kg). Use the entire Howell1 data frame, all 544 rows, adults and non-adults. Can you interpret the resulting estimates?
  (b) Begin with this plot: plot( height ~ weight , data=Howell1 ). Then use samples from the quadratic approximate posterior of the model in (a) to superimpose on the plot: (1) the predicted mean height as a function of weight, (2) the 97% interval for the mean, and (3) the 97% interval for predicted heights.

4H4. Plot the prior predictive distribution for the parabolic polynomial regression model in the chapter. You can modify the code that plots the linear regression prior predictive distribution. Can you modify the prior distributions of α, β1, and β2 so that the prior predictions stay within the bio- logically reasonable outcome space? That is to say: Do not try to fit the data by hand. But do try to keep the curves consistent with what you know about height and weight, before seeing these exact data.

4H5. Return to data(cherry_blossoms) and model the association between blossom date (doy) and March temperature (temp). Note that there are many missing values in both variables. You may consider a linear model, a polynomial, or a spline on temperature. How well does temperature trend predict the blossom trend?

4H6. Simulate the prior predictive distribution for the cherry blossom spline in the chapter. Adjust the prior on the weights and observe what happens. What do you think the prior on the weights is doing?

4H8. The cherry blossom spline in the chapter used an intercept α,but technically it doesn’t require one. The first basis functions could substitute for the intercept. Try refitting the cherry blossom spline without the intercept. What else about the model do you need to change to make this work?